### ISSUE TITLE
Content appears briefly before disappearing

### ISSUE THREAD

**Issue by MattF-Afterpay** [debs-obrien/debbie.codes#400]
Hi!

I am trying to browse the following page: https://debbie.codes/blog/nuxt-image/
The content of the page briefly shows for a second before disappearing.
I've tried with adblocker disabled on the following:
- Chrome _(desktop)_
- Firefox _(desktop)_
- Safari _(mobile)_

Behavior is the same on all browsers I've tested.

https://user-images.githubusercontent.com/61439100/203436282-e6b9d2ca-15d4-4d37-81a3-d17e1fc2f08a.mov

**Comment by debs-obrien** [comment]
Hi, thanks for reporting. I believe this is coming from the NuxtImg tag being used in Nuxt content as have errors in dev and images are not rendering. Have reported to Nuxt team and in meantime have removed NuxtImg from md and replaced with img tag. when pr is merged please check again and let me know if it fixes it for you. Of course it works on my machine ;)

https://github.com/debs-obrien/debbie.codes/pull/401

**Comment by debs-obrien** [comment]
it was actually the asyncData was missing from the queries which is necessary when running in static mode. it should all work now as soon as merged. thanks again

https://github.com/debs-obrien/debbie.codes/pull/403
